### PR TITLE
Bug/1048 memberships not added

### LINKED ISSUE #1048: Memberships cannot be added to projects
The membership appears to be added successfully but when you refresh the page it disappears.

### PR DESCRIPTION
**Pull request by AnkyrinRepeat**
Closes #1048.

Creates/destroys group_staff association when creating a new group and updating a group. Orders groups ascending by id so order isn't changed by updating them.

### CODE REVIEW

File: app/controllers/groups_controller.rb [hunk 1]
```diff
@@ -61,12 +65,29 @@ def destroy
...
+    end
+  end
+
   def group_params
     params.permit :name, :description, :staff_ids
   end
 
   def groups
-    @_groups ||= query_with Group.all, :includes, :pagination
+    @_groups ||= query_with Group.order('id').all, :includes, :pagination
```
Comment (stackus) [inline app/controllers/groups_controller.rb]: Why are you adding an order by `id` here?

**Comment by stackus** [comment]
Does this change keep the `staff_count` up to date as staff are added and removed?

File: app/controllers/groups_controller.rb (hunk 1 above)
Comment (AnkyrinRepeat) [inline app/controllers/groups_controller.rb]: Otherwise it orders the groups by updated_at, so if you change a group it gets dropped to the bottom of the list.

**Comment by AnkyrinRepeat** [comment]
screen shot 2015-11-17 at 4 46 52 pm

Staff Count is updated when you add/subtract members from a group.

**Comment by stackus** [comment]
:+1:
