### PR TITLE
Bug/791 project serializer related data

### LINKED ISSUE #791: Data returned from ProjectSerializer strips relation data
- [x] Add missing `*_serializer.rb` files for any related data in `project_serializer.rb`.
- [x] Serializer relation DSL does not accept additional parameters so things like `through:`, `class_name:`, ... can be removed

### PR DESCRIPTION
**Pull request by OBCENEIKON**
Fixes #791

### CODE REVIEW

File: app/serializers/membership_serializer.rb [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+#  role_id    :integer
+#
+# Indexes
+#
+#  index_memberships_on_group_id    (group_id)
+#  index_memberships_on_project_id  (project_id)
+#
+
+class MembershipSerializer < ApplicationSerializer
+  attributes :id, :created_at, :updated_at
```
Comment (stackus) [inline app/serializers/membership_serializer.rb]: We may want to include `:group_id, :project_id, :role_id` in the `attributes` list and then also add the relationships.

```
has_one :group
has_one :project
has_one :role
```
