### PR TITLE
Fixes issue with parameters. Also removes staff_id parameter and only…

### LINKED ISSUE #789: Changes and additions to MOTD API
- [x] Endpoint to retrieve the latest MOTD
- [x] Ensure users aren't posting MOTDs as others.  We shouldn't accept `staff_id` from params and should instead assign it from `current_staff.id`.

### PR DESCRIPTION
**Pull request by OBCENEIKON**
… allows for one MOTD to exist.

Fixes #789

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -153,7 +153,17 @@
     resources :tags, only: [:index]
 
     # MOTD Routes
-    resources :motd
+    # collection do
```
Comment (stackus) [inline config/routes.rb]: comments

File: config/routes.rb [hunk 2]
```diff
@@ -153,7 +153,17 @@
...
+    #   get :motd
+    #   post :motd
+    #   patch :motd
+    #   patch :motd
+    #   delete :motd
+    # end
+    get :motd, to: 'motd#index'
```
Comment (stackus) [inline config/routes.rb]: Does `resource :motd` do the same as these? Notice `resource` is singular.

Comment (OBCENEIKON) [inline config/routes.rb]: This eliminates the need to pass and id. Since there will ever only be one MOTD, we just do a first_or_initialize in the controller.

File: config/routes.rb [hunk 3]
```diff
@@ -153,7 +153,10 @@
     resources :tags, only: [:index]
 
     # MOTD Routes
-    resources :motd
+    get :motd, to: 'motd#index'
```
Comment (stackus) [inline config/routes.rb]: To follow-up on my last comment. The route system has both a `resources` and a `resource` helper. The first sets up routes which will require ids, the second is for things that there is only one of and so no ids are needed.

Link again to the documentation for `resource`: http://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resource

File: app/policies/motd_policy.rb [hunk 4]
```diff
@@ -1,11 +1,9 @@
 class MotdPolicy < ApplicationPolicy
-  def index?
-    true
-  end
+  # def initialize(user, record); end
 
-  def show?
-    true
-  end
+  # def show?
```
Comment (stackus) [inline app/policies/motd_policy.rb]: comments

**Comment by stackus** [comment]
@OBCENEIKON Please remove the comments and then fix the merge conflicts so this can be merged.
